# Default locale for UI strings
# Available UI languages: en, fr, de, sv
locale: "en"

# Available themes: bulma, chota, dsfr
# You can set the theme on the command line with
# clj -X:set :theme bulma
theme: "bulma"

# Customize UI strings
ui-strings:
  # copy-to-clipboard:    "Copy in the clipboard"
  # mail-to-message:      "Send by email"
  # mail-subject:         "Results"
  # mail-body:            "Hi,\n%s\nThanks."
  # redo:                 "Redo"
  # ok:                   "Okay"
  # contact-intro:        "Contact: "
  # toggle-summary-style: "Toggle summary style"
  # attention:            "Attention"

# Website header
header:
 title:    "Here is my title."
 subtitle: "A subtitle here, possibly with _markdown_ formatting."

# Website footer
footer:
 text:    "Some text here, possibly with **markdown** formatting."
 contact:  "bzg@gnu.org"

# Allow users to send you emails with the summary?
mail-to: "bzg@gnu.org"

# Display summary when done?
display-summary: true

# Display score information?
display-score: true

# Display each score?
# Mostly useful for debugging
display-score-details: false

# Display the score with the highest value?
# Only when :as-top-result-display is set for each score
display-score-top-result: false

# In a branch of the tree, should the target node be set depending on
# the updated value of conditional-score-output?
conditional-navigation: false

# Some text message to always display after the score results
display-unconditionally: false

# Set initial variables to register scores.
score-variables:
  # "score-1" is a user-defined string
  score-1:
    # What to display when displaying score details:
    display: "Score for 1"
    # Initial value for score-1:
    value: 0
    # When you when the score message to use percent:
    as-percent: true
    # Max is needed for displaying percent:
    max: 3
    # Only needed when display-score-top-result is true
    as-top-result-display: "1 wins :)"

# Set conditional output depending on scores.
conditional-score-output:
  # Cases are tested one by one.  The first case that matches is the
  # main score.  When case have a priority value, the matching case
  # with the highest priority is the main score.
  cas-1: # free-form condition name
    # priority: 2 # Use priority to matching order
    color: "is-success" # Bulma-based class names for the UI
    # notification.  Available values for colors are: is-success,
    # is-info, is-warning, is-danger.
    message: "Here is the score 1: %score-1%"
    # In score-variables, when :max is set and :as-percent is true,
    # then the score will be shown as a percentage.
    condition-1:
      score-1: 2 # This condition is met when score-1 is >= 2
  cas-2:
    color: "is-warning"
    message: "Here is the score 1: %score-1%"
    condition-1:
      score-1: 1 # This condition is met when score-1 is >= 1
  cas-3:
    color: "is-danger"
    message: "Here is the score 1: %score-1%"
    condition-1:
      score-1: 0 # This condition is met when score-1 is >= 0

# Mandatory configuration option
tree:
  - node:       "0"
    text:       "A title for the default page"
    home-page:  true
    no-summary: true
    help:       "Some introductory text here."
    choices:
    - answer: "Start now"
      goto:   "1"
      color:  "is-info"

  - node:       "1"
    progress:   "[0 3]"
    text:       "Is it the first question?"
    help:       "Some **help text** here for the first question.  Markdown formatting accepted."
    start-page: true
    choices:
    - answer:  "Yes"
      summary: "Yes, this is the first question."
      explain: "Some explanation here."
      score:
        score-1:
          value: 1
      goto:    "2"
      color:   "is-success"
    - answer:  "No"
      summary: "No, this is not the first question."
      color:   "is-danger"
      goto:    "end"

  - node:     "2"
    progress: "[1 3]"
    text:     "Is it the second question?"
    help:     "Some help text here for the second question."
    choices:
    - answer:  "Yes"
      summary: "Yes, this is the second question!"
      score:
        score-1:
          value: 1
      goto:    "3"
      color:   "is-success"
    - answer:  "Maybe"
      summary: "This is the second question, maybe."
      goto:    "3"
      color:   "is-info"
    - answer:  "No"
      summary: "No, this is not the second question."
      color:   "is-danger"
      goto:    "end"

  - node:     "3"
    progress: "[2 3]"
    text:     "Is it the _third_ question?"
    choices:
      - answer:  "Yes"
        summary: ["Yes, this is the third question...", "This will end soon, I promise."]
        goto: "end"
        color: "is-success"
        score:
          score-1:
            value: 1
      - answer:  "No"
        summary: "No, this is not the third question."
        color: "is-danger"
        goto: "end"

  - node: "end"
    progress: "[3 3]"
    text: "This is the end."
    done: true
