/**********************************************************************
 * Extern for ClipboardJS
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ClipboardJS = function () {};
ClipboardJS.prototype = {
    "emit": function () {},
    "off": function () {},
    "on": function () {},
    "once": function () {}
};
/**********************************************************************
 * End Generated Extern for ClipboardJS
/**********************************************************************/
